language: cpp

before_install:
  - sudo apt update
  - sudo apt -y install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libpthread-stubs0-dev

script:
  - mkdir out && cd out
  - qmake ../RR.pro && make
  - ./RR

notifications:
  email:
    recipients:
      - lets_blu@outlook.com
  on_success: always
  on_failure: always
