language: cpp

before_install:
  - sudo apt update
  - sudo apt install -f qt5-default valgrind

script:
  - mkdir out && cd out
  - qmake ../RR.pro && make
  - valgrind --leak-check=full --show-leak-kinds=all --log-file=valgrind.log ./RR

after_success:
  - cat valgrind.log
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - lets_blu@outlook.com
  on_success: always
  on_failure: always
