language: cpp

before_install:
  - sudo apt update
  - sudo apt install -f qt5-default

script:
  - mkdir out && cd out
  - qmake ../RR.pro && make

after_success:
  - ./RR
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - lets_blu@outlook.com
  on_success: always
  on_failure: always

